services:

  spacecowboys-service:
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    env_file: .env
    ports:
      - 5000:8080
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  spacecowboys-app:
    build:
      context: ./app
      args:
        APIBASE: "http://localhost:5000"
        LOGLEVEL: "debug"
    ports:
      - 8000:3000