name: Spacecowboy service tests and build

on:
  push:
    branches: [ main ]
    paths:
      - "src/**"
      - "test/**"
      - ".github/workflows/service.yml"
  pull_request:
    branches: [ main ]
    paths:
      - "src/**"
      - "test/**"
      - ".github/workflows/service.yml"

jobs:

  # Run all project tests.
  test:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore service dependencies
      run: dotnet restore ./src/Service.csproj

    - name: Build service
      run: dotnet build ./src/Service.csproj --no-restore

    - name: Restore test dependencies
      run: dotnet restore ./test/Service.Test.csproj

    - name: Build tests
      run: dotnet build ./test/Service.Test.csproj --no-restore

    - name: Run tests
      run: dotnet test ./test/Service.Test.csproj --no-build --verbosity normal


  # Build and push container image.
  build_container:

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [ test]

    steps:

    - uses: actions/checkout@v4

    - name: Setup Docker
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push container image
      uses: docker/build-push-action@v6
      with:
        context: src
        push: true
        tags: ghcr.io/spacecowboy-app/spacecowboy-service:latest
