name: Spacecowboy service tests and build

on:
  push:
    branches: [ main ]
    paths:
      - "service/src/**"
      - "service/test/**"
      - ".github/workflows/service.yml"
  pull_request:
    branches: [ main ]
    paths:
      - "service/src/**"
      - "service/test/**"
      - ".github/workflows/service.yml"

jobs:

  # Run all project tests.
  test:
    name: "Test service"

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: service

    steps:

    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore service dependencies
      run: dotnet restore ./src/Service.csproj

    - name: Build service
      run: dotnet build ./src/Service.csproj --no-restore

    - name: Restore test dependencies
      run: dotnet restore ./test/Service.Test.csproj

    - name: Build tests
      run: dotnet build ./test/Service.Test.csproj --no-restore

    - name: Run tests
      run: dotnet test ./test/Service.Test.csproj --no-build --verbosity normal


